### ISSUE TITLE
Custom Header Image

### ISSUE THREAD

**Issue by cyberfarer** [ItsAnilSingh/mudra#1]
Hello

Thank you for the theme. I am using a custom header image but it is repeating. I have attempted to use CSS to prevent that, but no luck. Can you help?

The css I tried is below:
`.custom-header .container { background-repeat: no-repeat !important;  }`

**Comment by ItsAnilSingh** [comment]
Hello @cyberfarer 

Looks like you opened an issue 20 days ago. I have not got any email regarding this, hence have not checked GitHub. You simply could have mentioned me while commenting or on the WordPress support forum or on my blog.

Anyways, you should be using the ID of the element, not the undefined class. Try this,

`#custom-header { background-repeat: no-repeat !important; }`
